backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    label_singular: "Blogartikel"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "events"
    label: "Evenementen"
    label_singular: "Evenement"
    folder: "src/content/agenda"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "event"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Event Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "trainingSchedules"
    label: "Trainingen"
    label_singular: "Trainingstabel"
    folder: "src/content/trainings"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "event"}
      - {label: "Title", name: "title", widget: "string"}
      - label: "Trainingstype"
        name: "type"
        widget: "select"
        options: ["veld", "zaal"] 
      - label: "Trainingen"
        label_singular: "Training"
        name: "trainings"
        widget: "list"
        fields: 
        - label: "Trainingsdag"
          name: "day"
          widget: "select"
          options: ["maandag", "dinsdag", "woensdag", "donderdag", "vrijdag", "zaterdag", "zondag"]
        - {label: "Trainingstijd", name: "time", widget: "string"}
        - {label: "Opmerkingen", name: "remarks", widget: "text"}
        - {label: "Trainer", name: "trainer", widget: "text"}
        - label: "Teams"
          name: "trainingTeams"
          widget: "relation"
          collection: "teams"
          searchFields: ["teamName", "description"]
          valueField: "teamName"
          displayFields: ["teamName"]                 

  - name: "teams"
    label: "Teams"
    label_singular: "Team"
    folder: "src/content/teams"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "team"}
      - {label: "Teamnaam", name: "title", widget: "string"}
      - {label: "Teamfoto", name: "photo", widget: image, required: false}
      - {label: "Team-ID Zaal", name: "indoorId", widget: "string", required: false}
      - {label: "Team-ID Veld", name: "outdoorId", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - label: "Spelers"
        name: "players"
        widget: "list"
        fields:
          - {label: "Openbaar", name: "public", widget: "boolean", default: true}
          - {label: "Naam", name: "name", widget: "string"}
          - {label: "Foto", name: "photo", widget: "image", required: false}

  - name: "pages"
    label: "Pagina's"
    label_singular: "Pagina"
    files:
      - file: "src/content/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/content/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
